[phases.setup]
nixPkgs = [
    "python312",
    "python312Packages.pip",
    "pango",
    "cairo",
    "gdk-pixbuf",
    "libffi",
    "fontconfig",
    "freetype",
    "harfbuzz",
    "gobject-introspection",
    "glib",
    "dejavu_fonts"
]

[phases.install]
cmds = [
    "python -m venv /app/.venv",
    ". /app/.venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = []

[variables]
LD_LIBRARY_PATH = "/root/.nix-profile/lib"
GI_TYPELIB_PATH = "/root/.nix-profile/lib/girepository-1.0"
XDG_DATA_DIRS = "/root/.nix-profile/share"
FONTCONFIG_PATH = "/root/.nix-profile/etc/fonts"

[start]
cmd = ". /app/.venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT"
